before:
  hooks:
    - go mod tidy

builds:
- main: cmd/nuclei/main.go
  binary: nuclei
  id: nuclei-cli

  env:
  - CGO_ENABLED=0

  goos: [windows,linux,darwin]
  goarch: [amd64,386,arm,arm64]
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64

  flags:
    - -trimpath

#- main: cmd/tmc/main.go
#  binary: tmc
#  id: annotate
#
#  env:
#  - CGO_ENABLED=0
#
#  goos: [linux]
#  goarch: [amd64]

archives:
- format: zip
  id: nuclei
  builds: [nuclei-cli]
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256

announce:
  webhook:
    # Whether its enabled or not.
    enabled: false

    # Check the certificate of the webhook.
    skip_tls_verify: true

    # Message template to use while publishing.
    #
    # Default: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'
    # Templates: allowed
    message_template: '{ "title": "Awesome project {{.Tag}} is out!"}'

    # Content type to use.
    #
    # Default: 'application/json; charset=utf-8'
    content_type: "application/json"

    # Endpoint to send the webhook to.
    endpoint_url: "https://example.com/webhook"
    # Headers to send with the webhook.
    # For example:
    # headers:
    #   Authorization: "Bearer <token>"
    headers:
      User-Agent: "goreleaser"
