name: 🎉 Release Binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs: 
  release: 
    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with: 
          go-version: 1.21.x

      - uses: goreleaser/goreleaser-action@v4
        with: 
          args: "release --clean"
          version: latest
        env: 
          GITHUB_TOKEN: "${{ secrets.NUCLEI_GITHUB_TOKEN }}"
